PACKAGE_NAME="gigabyte_waterforce"
PACKAGE_VERSION="1.0.0"

BUILT_MODULE_NAME[0]="gigabyte_waterforce"
BUILT_MODULE_LOCATION[0]="drivers/hwmon/"
DEST_MODULE_LOCATION[0]="/updates/dkms/"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"

AUTOINSTALL="yes"
